export const usaState = [
  {
    id: 1,
    engName: "California",
    uaName: "Каліфорнія ",
    ruName: "Калифорния",
  },
  {
    id: 2,
    engName: "Texas",
    uaName: "Техас ",
    ruName: "Техас",
  },
  {
    id: 3,
    engName: "Florida",
    uaName: "Флорида ",
    ruName: "Флорида",
  },
  {
    id: 4,
    engName: "New York",
    uaName: "Нью-Йорк  ",
    ruName: "Нью-Йорк",
  },
  {
    id: 5,
    engName: "Illinois",
    uaName: "Іллінойс ",
    ruName: "Иллинойс",
  },
  {
    id: 6,
    engName: "Pennsylvania",
    uaName: "Пенсильванія",
    ruName: "Пенсильвания",
  },
  {
    id: 7,
    engName: "Ohio",
    uaName: "Огайо",
    ruName: "Огайо",
  },
  {
    id: 8,
    engName: "Georgia",
    uaName: "Джорджія",
    ruName: "Джорджия",
  },
  {
    id: 9,
    engName: "North Carolina",
    uaName: "Північна Кароліна",
    ruName: "Северная Кароліна",
  },
  {
    id: 10,
    engName: "Michigan",
    uaName: "Мічиган",
    ruName: "Мічиган",
  },
  {
    id: 11,
    engName: "New Jersey",
    uaName: "Нью-Джерсі",
    ruName: "Нью-Джерси",
  },
  {
    id: 12,
    engName: "Virginia",
    uaName: "Вірджинія",
    ruName: "Вирджиния",
  },
  {
    id: 13,
    engName: "Washington",
    uaName: "Вашингтон",
    ruName: "Вашингтон",
  },
  {
    id: 14,
    engName: "Arizona",
    uaName: "Аризона",
    ruName: "Аризона",
  },
  {
    id: 15,
    engName: "Massachusetts",
    uaName: "Массачусетс",
    ruName: "Массачусетс",
  },
  {
    id: 16,
    engName: "Indiana",
    uaName: "Індіана",
    ruName: "Индиана",
  },
  {
    id: 17,
    engName: "Tennessee",
    uaName: "Теннессі",
    ruName: "Теннесси",
  },
  {
    id: 18,
    engName: "Missouri",
    uaName: "Міссурі",
    ruName: "Миссури",
  },
  {
    id: 19,
    engName: "Maryland",
    uaName: "Меріленд",
    ruName: "Мериленд",
  },
  {
    id: 20,
    engName: "Wisconsin",
    uaName: "Вісконсин",
    ruName: "Висконсин",
  },
  {
    id: 21,
    engName: "Minnesota",
    uaName: "Міннесота",
    ruName: "Миннесота",
  },
  {
    id: 22,
    engName: "Colorado",
    uaName: "Колорадо",
    ruName: "Колорадо",
  },
  {
    id: 23,
    engName: "South Carolina",
    uaName: "Південна Кароліна",
    ruName: "Южная Каролина",
  },
  {
    id: 24,
    engName: "Alabama",
    uaName: "Алабама",
    ruName: "Алабама",
  },
  {
    id: 25,
    engName: "Louisiana",
    uaName: "Луїзіана",
    ruName: "Луизиана",
  },
  {
    id: 26,
    engName: "Kentucky",
    uaName: "Кентуккі",
    ruName: "Кентукки",
  },
  {
    id: 27,
    engName: "Oregon",
    uaName: "Орегон",
    ruName: "Орегон",
  },
  {
    id: 28,
    engName: "Oklahoma",
    uaName: "Оклахома",
    ruName: "Оклахома",
  },
  {
    id: 29,
    engName: "Connecticut",
    uaName: "Коннектикут",
    ruName: "Коннектикут",
  },
  {
    id: 30,
    engName: "Iowa",
    uaName: "Айова",
    ruName: "Айова",
  },
  {
    id: 31,
    engName: "Utah",
    uaName: "Юта",
    ruName: "Юта",
  },
  {
    id: 32,
    engName: "Mississippi",
    uaName: "Міссісіпі",
    ruName: "Миссисипи",
  },
  {
    id: 33,
    engName: "Arkansas",
    uaName: "Арканзас",
    ruName: "Арканзас",
  },
  {
    id: 34,
    engName: "Kansas",
    uaName: "Канзас",
    ruName: "Канзас",
  },
  {
    id: 35,
    engName: "Nevada",
    uaName: "Невада",
    ruName: "Невада",
  },
  {
    id: 36,
    engName: "New Mexico",
    uaName: "Нью-Мексико",
    ruName: "Нью-Мексико",
  },
  {
    id: 37,
    engName: "Nebraska",
    uaName: "Небраска",
    ruName: "Небраска",
  },
  {
    id: 38,
    engName: "Western Virginia",
    uaName: "Західна Вірджинія",
    ruName: "Западная Верджиния",
  },
  {
    id: 39,
    engName: "Idaho",
    uaName: "Айдахо",
    ruName: "Айдахо",
  },
  {
    id: 40,
    engName: "Hawaii",
    uaName: "Гаваї",
    ruName: "Гаваи",
  },
  {
    id: 41,
    engName: "New Hampshire",
    uaName: "Нью-Гемпшир",
    ruName: "Нью-Гемпшир",
  },
  {
    id: 42,
    engName: "Maine",
    uaName: "Мен",
    ruName: "Мен",
  },
  {
    id: 43,
    engName: "Rhode Island",
    uaName: "Род-Айленд",
    ruName: "Род-Айленд",
  },
  {
    id: 44,
    engName: "Montana",
    uaName: "Монтана",
    ruName: "Монтана",
  },
  {
    id: 45,
    engName: "Delaware",
    uaName: "Делавер",
    ruName: "Делавер",
  },
  {
    id: 46,
    engName: "South Dacota",
    uaName: "Південна Дакота",
    ruName: "Южная Дакота",
  },
  {
    id: 47,
    engName: "North Dacota",
    uaName: "Північна Дакота",
    ruName: "Северная Дакота",
  },
  {
    id: 48,
    engName: "Alaska",
    uaName: "Аляска",
    ruName: "Аляска",
  },
  {
    id: 49,
    engName: "Vermont",
    uaName: "Вермонт",
    ruName: "Вермонт",
  },
  {
    id: 50,
    engName: "Wyoming",
    uaName: "Вайомінг",
    ruName: "Вайоминг",
  },
  {
    id: 51,
    engName: "District of Columbia",
    uaName: "Округ Колумбія",
    ruName: "Округ Колумбия",
  },
  {
    id: 52,
    engName: "Puerto Rico",
    uaName: "Пуерто-Ріко",
    ruName: "Пуерто-Рико",
  },
];
